### ISSUE TITLE
Review and verify the milestone of Runtime verification contract

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#248]
This specifically concerns fulfillment of milestone 2 and milestone 3:

 - Milestone 2
  - [ ] Develop abstract K specifications at the Wasm level of the balances runtime module. These specifications will mimic the Rust data-structures directly as K terms. An example of this for the set_free_balance method can be found here: https://github.com/runtimeverification/polkadot-verification/blob/master/set-free-balance.md. A person from Runtime Verification Inc. will assist in developing the remaining high-level specs, but it's understood that Polkadot devs should take over this process. Call this specification BALANCES-MODULE-SPEC.
  - [ ] Produce documentation describing the specification, including the high-level English specification and arguments that the K specification is a refinement of the English specification.

 - Milestone 3: Generate the Wasm execution specifications of the bytecode:
  - [ ] Generate execution traces of the Wasm code using the LLVM backend and a fuzzing frontend. This will produce sequences of rules in the order that they are executed, called BALANCES-MODULE-TRACE_i (subscripted by _i for the fact that there are many traces).
  - [ ] Do common subsequence analysis on the BALANCES-MODULE-TRACE_i to find common subsequences of rules, and ask the Haskell backend to merge those rules together into rules which take larger steps. Several heuristics for rule merging will be provided, which select different subsequences to do merging with, and we can see which ones perform best.
  - [ ] Compile the generated merged rules into the semantics with higher priority than the original rules, so that they can be used for both symbolic and concrete execution.

**Comment by FlorianFranzen** [comment]
I had a first meeting with @Lederstrumpf last week, getting the environment for the testing set up. This is what we settled one:

 1. Pull the k-framework from Docker Hub*
 2. Start the container and install missing dependecies:
    - Update package cache `apt-get update`
    - Install pandoc, python3 and your favorite editor (e.g. `apt-get install pandoc python3 vim`)
 3. Check out the repo into the container as well (e.g. `git clone --recurse-submodules https://github.com/runtimeverification/polkadot-verification.git`)
 4. Generate the necessary traces (`make build` and `make build BUILD=coverage`)
 5. Test functionality (`make prove-specs`, `make test-python-config` and `make test-search`)

*The correct k-framework version can be determine based on the git revision in the submodule `deps/wasm-semantics/deps/k`. The image name is then `runtimeverificationinc/kframework-k:ubuntu-bionic-<rev>`.

**Comment by Lederstrumpf** [comment]
> I had a first meeting with @Lederstrumpf last week, getting the environment for the testing set up. This is what we settled one:
> 
> 1. Pull the k-framework from Docker Hub*
> 2. Start the container and install pandoc and your favorite editor (e.g. `apt-get install pandoc vim`)
> 3. Check out the repo into the container as well (e.g. `git clone --recurse-submodules https://github.com/runtimeverification/polkadot-verification.git`)
> 4. Generate the necessary traces (`make build` and `make build BUILD=coverage`)
> 5. Test functionality (`make prove-specs`, `make test-python-config` and `make test-search`)
> 
> *The correct k-framework version can be determine based on the git revision in the submodule `deps/wasm-semantics/deps/k`. The image name is then `runtimeverificationinc/kframework-k:ubuntu-bionic-<rev>`.

LGTM. To run `make test-python-config`, you'll still have to `apt update && apt install python3`.

**Comment by FlorianFranzen** [comment]
Milestone 3 will require some more in-depth analysis of the Python and PyK code that performs these steps to complete the review.

**Comment by lamafab** [comment]
@Noc2 says this is done.
