### ISSUE TITLE
Add fixture to test fork behavior of implementations

### ISSUE THREAD

**Issue by FlorianFranzen** [w3f/polkadot-spec#273]
We want to extend out test suite with more integrated tests, with an initial focus on state-machine and consensus behavior.

The first scenario we would like to implement a fork, where two blocks were produced in the same slot by different entities.

### Tasks
 - [ ] Choose file format for chain state (needs to be able to represent forks)
 - [ ] Create or export file representing chain state with fork
 - [ ] Find a way to load state for each implementation
 - [ ] Determine how to check outcome, e.g. state export, custom runtime, rpc
 - [ ] Put it all together in new `fork` fixture

Feel free to take some inspiration from the [Ethereum test suite](https://ethereum-tests.readthedocs.io/en/latest/testsuite.html) to how this could be done.

**Comment by lamafab** [comment]
* @lamafab will work on this after the registrar project has been stabilized.

**Comment by lamafab** [comment]
The ethereum test suite is quite impressive. They have a repos which only contains raw test cases and results in JSON format. Then, they have a separate tester binary:
- https://github.com/ethereum/tests
- https://github.com/ethereum/retesteth

We should definitely do it similarly. While we already have "fixtures", those are mostly lists speads among multiple files. Moving forward, we should make the data and all associated results isolated to a single file, for each test case, even though this will probably cause redudancy. One should not have to look at the code in order to figure out what the test cases and their corresponding results are (maybe Florian already adjusted that with the current tests that we have with the Host API).

In case of the Ethereum, the tester uses RPC calls to test the implementation. We should consider doing that too. Implementers should not create custom low-level functionality in order to use the tests. Ideally any other implementers should just reimplement the RPC API (I also opened this issue https://github.com/w3f/polkadot-spec/issues/306). This way, implementers can just use the existing tester in order to test their implementation.

Anyway, I propose:
- Create test cases with standardized JSON formats. We will have a different format for each test type. Each format should be proposed. Additionally, each format should have the same header.

Example:
```json
{
  "name": "Finalize fork",
  "type": "BlockChainFork",
  "descritpion": "Mutliple blocks were produced in the same slot by different authors",
  "required_rpc_apis": [
    "author_submitExtrinsic",
    "engine_finalizeBlock"
  ],
  "pre_state": {
    ...
  },
  "events": {
    ...
  }
  "post_state": {
    ...
  }
}
```
- Write a custom tester which reads the test cases and calls the required methods. The tester should be very simple:
  - Read the JSON file and interpret it.
  - Replicate the pre state.
  - Call the RPC methods with the test data.
  - Check the correctness by verifying the post state.
- Create a new repo for just the test cases (fixtures and results)

Any thoughts?

**Comment by drskalman** [comment]
@FlorianFranzen will update the ticket based on the discussion we had in the meeting and we ll have another meeting to maturing the bootstraping process.

**Comment by drskalman** [comment]
@lamafab nonetheless starts with minimum spec and then we add more feature and spec along the way.

**Comment by lamafab** [comment]
@lamafab Will work on this based on the following proposal:

***
# Fork Testing

Those tests verify whether the Polkadot Host implementation can correctly
transition between forks.

## Description

The testing data includes block chains which contain forks, meaning that
multiple blocks are built on top of the same parent block. Each block must only
have access to the data of the fork it is on. The storage space must therefore
be segregated based on those forks.

Those are basic concepts that a state machine is supposed to support.

## Requirements

The Polkadot Host implementation must offer the following functionality:

* Import a genesis state from file (see specification ...).
* Import and execute a block from file (see specification ...).
    * The block is executed by sending it to the `Core_execute_block` runtime function.

## Testing Process

The Polkadot Host implementation loads the genesis state as specified in the
`genesis.json` file. The genesis state includes the custom Runtime (compiled
from `src/runtime/`) which creates a log statement of the state root after a
block is executed by calling the `Core_execute_block` runtime function. The
tester captures that log statement and compares it against the expected result.

After each block is executed and the comparison of the log statement and the
expected result is valid, the Polkadot Host implementation is compliant.

### Workflow

* Import genesis state.
* For each block:
    * Execute block.
    * Capture log statement.
    * Compare the log statement to the expected result.

## Test Data

Multiple tests can be found in the `tests/` directory. Each test is structured as:

```json
{
   "name":"Fork Awareness",
   "type":"BlockChainFork",
   "description":"Multiple blocks were produced on the same parent block",
   "genesis":"genesis.json",
   "blocks":{
      "block":{
         "header":{
            "parentHash":"0xd380bee22de487a707cbda65dd9d4e2188f736908c42cf390c8919d4f7fc547c",
            "number":"0x5",
            "stateRoot":"0x01045dae0c5d93a84c3dc1f0131126aa6aa1feb26d10f029166fc0c607468968",
            "extrinsicsRoot":"0xa9439bbc818bd95eadb2c5349bef77ee7cc80a282fcceb9670c2c12f939211b4",
            "digest":{
               "logs":[
                  "0x0642414245b50103000000009ddecc0f00000000a8a9c1d717f3904506e333d0ebbf4eed297d50ab9b7c57458b10182f1c84025ef09d3fb5b5f4cb81688939e6363f95aa8d91645fa7b8abc0a6f37812c777c307df51071082d3ff89d4e1b5ad8f5cd3711ada74292c4808237bdf2b076edb280c",
                  "0x05424142450101f66230eb71705213dd10256e3ca5af07492ac420128ecb8bc98f1fcd1f74986d348addbabd4813f0022835b21d720ecadce66a57480d87dfd51d77f3474cb68b"
               ]
            }
         },
         "extrinsics":[
            "0x280403000bb07fa1517201",
            "0x1004140000"
         ],
         "post_state": "0x8d4ea2ea4e834faa1ed492f66f0b28ea56fc9061b7e89623114968e2cf59987a"
      },
      "block": {
          ...
      }
   }
}
```

After the tester runs the Polkadot Host implementation with the specified genesis
state, it must execute each block and check the log statement created by the
Runtime against the `post_state` result.

***

**Comment by lamafab** [comment]
I'm currently writing the toolkit to generate transactions and the block building procedure. Transaction generation is completed, block builder process should be done in the next few days.

**Comment by FlorianFranzen** [comment]
@lamafab finishes factory tool. @FlorianFranzen will write Julia testfixture once merged (see #322).

**Comment by drskalman** [comment]
There is glitch with signing the extrinsics. @lamafab  will explore using offchain worker to sign them.

**Comment by drskalman** [comment]
Waiting still on #322 merger.
