### ISSUE TITLE
Review GRANDPA related Kagome issues on gitlab

### ISSUE THREAD

**Issue by drskalman** [w3f/polkadot-spec#396]
This a reference issue to keep track of the progress on remaining issues on gitlab resulting from Kagome GRANDPA implementation. Clarification has been provided to these issues:

proposing.
 - [ ] [#30](https://gitlab.w3f.tech/grants/soramitsu/-/issues/30) VotingRoundImpl::validate ignores equivocatation.
 - [x] [#16](https://gitlab.w3f.tech/grants/soramitsu/issues/16) Can not find Grandpa networking and actual message sending
 - [x] [#15](https://gitlab.w3f.tech/grants/soramitsu/issues/15) Blocks not having anscestor in vote graph should not be considered to be ghost
 - [x] [#14](https://gitlab.w3f.tech/grants/soramitsu/-/issues/14) ·No matter how the estimate is finalized it should stop primary from  - 
 - [ ] [#12](https://gitlab.w3f.tech/grants/soramitsu/-/issues/12) if last_round_state.estimate: doesn't exitst then it should be an error
 - [ ] [#10](https://gitlab.w3f.tech/grants/soramitsu/issues/10) Host should not directly access the state storage

These issues are needed to be reviewed.

 - [x] [#27](https://gitlab.w3f.tech/grants/soramitsu/-/issues/27) Honest voter must precommit
 - [x] [#29](https://gitlab.w3f.tech/grants/soramitsu/-/issues/29) OnPropose does not verify the validity of the signature of the proposer
 - [x] [#25](https://gitlab.w3f.tech/grants/soramitsu/-/issues/25) finalized block definition in VotingRoundImpl::update() seems to be wrong
 - [x] [#22](https://gitlab.w3f.tech/grants/soramitsu/-/issues/22) GRANDPA Prevote and Precommit signature doesn't seem to be checked
 - [ ] [#19](https://gitlab.w3f.tech/grants/soramitsu/-/issues/19) FindMergePoint assumes that there is only one descendent which can pass the threshold
 - [ ] [#18](https://gitlab.w3f.tech/grants/soramitsu/-/issues/18) Verify that the search actually produce the GHOST as defined in the spec

**Comment by drskalman** [comment]
Reviewed 22-30 and left comment for follow up to [#30](https://gitlab.w3f.tech/grants/soramitsu/-/issues/30) and  [#27](https://gitlab.w3f.tech/grants/soramitsu/-/issues/27) and resolved the rest.

**Comment by drskalman** [comment]
Reviewed:
 - [#12](https://gitlab.w3f.tech/grants/soramitsu/-/issues/12) Left a comment, for assert failure and panicking.
 - [#14](https://gitlab.w3f.tech/grants/soramitsu/-/issues/14) Left a comment, the logic still seems to be wrong.
 - [#18](https://gitlab.w3f.tech/grants/soramitsu/-/issues/18) I need @AlistairStewart to verify GHOST is coming out of BFS or DFS. 
  
Still need to be reviewed:
  - [#19](https://gitlab.w3f.tech/grants/soramitsu/-/issues/19)

**Comment by drskalman** [comment]
Reviewing following issues after new updates from Kagome team:

  - https://gitlab.w3f.tech/grants/soramitsu/-/issues/30 reflected in https://github.com/soramitsu/kagome/pull/761
  I somehowo have hard time understanding this process: https://github.com/soramitsu/kagome/blob/323637c552baba92fda44ddcf2d3bd1cd4da693c/core/consensus/grandpa/impl/vote_tracker_impl.cpp#L27

**Comment by drskalman** [comment]
Reposted the comment on gitlab on github in hope to be review and changed the status of https://gitlab.w3f.tech/grants/soramitsu/-/issues/14 back to in-development.

**Comment by FlorianFranzen** [comment]
@drskalman will update the issue and sort outstanding problems into syncing and producing related, so they can be discussed alongside the next workplan.

**Comment by drskalman** [comment]
Update: I talked to @AlistairStewart on #18: He agrees that it should be BFS.

**Comment by drskalman** [comment]
Reviewed replyed to [#15](https://gitlab.w3f.tech/grants/soramitsu/-/issues/15) and closed it.

**Comment by drskalman** [comment]
Closed
 - [#27](https://gitlab.w3f.tech/grants/soramitsu/-/issues/27)
 - [#16](https://gitlab.w3f.tech/grants/soramitsu/-/issues/16)
 - [#14](https://gitlab.w3f.tech/grants/soramitsu/-/issues/14)

**Comment by drskalman** [comment]
> Update: I talked to @AlistairStewart on #18: He agrees that it should be BFS.

After discussion with @AlistairStewart according to this "if S is safe, then we can compute g(S) by starting at the genesis block and iteratively looking for a child of our current block with a supermajority, which must be unique if it exists" BFS and DFS ghosts will be the same if there is less than 1/3 equivocation and if more than 1/3 of validators equivocate, it is very hard for the honest validator to reach the same ghost even if they all use BFS or DFS.

On the other hand DFS is clearly more efficient here and it makes sense for the Spec to mandate DFS.

**Comment by drskalman** [comment]
Reviewed and closed gitlab issue [#18](https://gitlab.w3f.tech/grants/soramitsu/-/issues/18) in code in core/consensus/grandpa/vote_graph/vote_graph_impl.cpp

**Comment by drskalman** [comment]
Reviewed and closed gitlab issue [#28](https://gitlab.w3f.tech/grants/soramitsu/-/issues/28).

**Comment by drskalman** [comment]
Reviewed:
- [#11](https://gitlab.w3f.tech/grants/soramitsu/-/issues/11)
- [#12](https://gitlab.w3f.tech/grants/soramitsu/-/issues/12)

  commented and reassigned to @FlorianFranzen.

**Comment by drskalman** [comment]
- [#30](https://gitlab.w3f.tech/grants/soramitsu/-/issues/30)
  I do not agree with the conclusion. Reassigning to @Noc2.

**Comment by drskalman** [comment]
- [#26](https://gitlab.w3f.tech/grants/soramitsu/-/issues/26)
  Reassigned to @Noc2 to verify.

**Comment by Noc2** [comment]
It's been completed a long time ago.
