### ISSUE TITLE
Runtime API Spec: tracking issue

### ISSUE THREAD

**Issue by bhargavbh** [w3f/polkadot-spec#645]
Remaining tasks for Runtime API spec:

- [ ] define relevant datastructures like DisputeState, Executor Parameters, CandidateHash occurring in ParachainHostApi in AnV chapter and reference them. 
- [ ] document difference between RuntimeCall and Extrinsics and clarify the same in TransactionPaymentApi and TransactionPaymentCallApi
- [ ] add APIs on Beefy, MMR, and Staking Modules
